### ISSUE TITLE
e.target.closest in event-handler.js

### ISSUE THREAD

**Issue by chRohowski** [Veams/core#16]
**In event-handler.js line 47 of the helpers:**

`delegateTarget = e.target.closest(targetSelector);`

Is not workin in IE11 probably because it is no jQuery prototype?

**Maybe change it to:**

`delegateTarget = $(e.target).closest(targetSelector);`

Just my two cents.

Cheers
Christian

**Comment by Sebastian-Fitzner** [comment]
Nah, closest is a native function but you need to provide a polyfill for ie11 and below...

**Comment by Sebastian-Fitzner** [comment]
See also 
Element.closest() used in Line 54 of **/helpers/event-handler.ts** is not supported by Internet Explorer. You have to use a polyfill like [Polyfill for Element.closest()](https://developer.mozilla.org/en-US/docs/Web/API/Element/closest#Polyfill) to make this work.https://github.com/Veams/component/issues/1

**Comment by chRohowski** [comment]
Thanks Sebastian, that worked.

Added the node module "element-closest" and imported it into app.veams.js - if anybody wants to know ;)
