### ISSUE TITLE
Migration Guide

### ISSUE THREAD

**Issue by natrenakres** [Veams/core#20]
Hi All,

 We have Veams project and we want to update versions of core and related libraries. We use @veams/core 1.0.3 version. Do you have any migration guide from 1  version to 5? 

Thanks

**Comment by Sebastian-Fitzner** [comment]
Hi there,

as long as you have used `@veams/core` there should not be any major issue by updating to the latest version `1.1.1`. You only need to make sure, that your plugins are up-to-date as well ... 

Do you mind sending me your `package.json`?

**Comment by natrenakres** [comment]
Hi this is my `package.json`

> {
	"name": "lmu",
	"description": "Custom project description",
	"version": "0.0.1",
	"engines": {
		"node": "=8.11.3"
	},
	"scripts": {
		"clear:app": "rimraf app/**",
		"local:server": "cross-env BABEL_ENV=server nodemon src/server/index.js --config ./configs/tasks/nodemon.config.json",
		"prestart": "npm run clear:app",
		"start": "cross-env NODE_ENV=local npm-run-all --parallel local:*",
		"dev:build": "cross-env NODE_ENV=dev npm run build",
		"qa:build": "cross-env NODE_ENV=qa npm run build",
		"prod:build": "cross-env NODE_ENV=production npm run build",
		"local:start": "webpack --mode=development --watch --hide-modules",
		"build": "npm run clear:app && npm run handlebars:precompile && npm run sprite:generate && cross-env BABEL_ENV=client webpack --mode=development && npm run html:generate && npm run build:vue",
		"sprite:generate": "node configs/tasks/icons/sprite.js",
		"lint:styles": "stylelint src/app/**/*.scss --config configs/tasks/linting/stylelint.config.js",
		"lint:js": "eslint \"src/**/*.js\" --config configs/tasks/linting/eslintrc.js",
		"lint:fix": "npm run lint:js -- --fix && npm run lint:styles -- --fix",
		"images:generate": "node configs/tasks/images/images-resizer.js",
		"faker": "node configs/tasks/faker/faker.js",
		"html:generate": "node configs/tasks/mangony/mangony-build.js",
		"handlebars:precompile": "node configs/tasks/handlebars/precompile.js",
		"local:vue": "webpack --mode=development --watch --hide-modules --config webpack.vue.config.js",
		"build:vue": "webpack --mode=production --config=webpack.vue.config.js"
	},
	"dependencies": {
		"@veams/base": "^1.0.3",
		"@veams/component": "^1.2.3",
		"@veams/core": "^1.0.3",
		"@veams/helpers": "^1.2.0",
		"@veams/http-service": "^1.0.2",
		"@veams/plugin-dom": "^1.0.0",
		"@veams/plugin-logger": "^1.0.0",
		"@veams/plugin-media-query-handler": "^1.0.0",
		"@veams/plugin-mixins": "^1.0.0",
		"@veams/plugin-modules": "^1.2.0",
		"@veams/plugin-store": "^0.0.2",
		"@veams/plugin-templater": "^1.0.0",
		"@veams/plugin-vent": "^1.0.0",
		"@veams/query": "^2.4.0",
		"element-closest": "^2.0.2",
		"es6-promise": "^4.2.6",
		"handlebars": "^4.0.10",
		"lazysizes": "^4.0.1",
		"mutation-observer": "^1.0.3",
		"pikaday": "^1.8.0",
		"promise-polyfill": "^8.0.0",
		"respimage": "^1.4.2",
		"vue": "^2.6.5",		
		"vue-template-compiler": "^2.6.5",
		"vuex": "^3.1.0"
	},
	"devDependencies": {
		"@veams/bp-mock-api": "^1.0.3",
		"@veams/component-form": "^1.0.1",
		"@veams/component-slider": "^1.0.1",
		"aliasify": "^2.1.0",
		"autoprefixer": "^8.6.3",
		"babel-core": "^6.26.3",
		"babel-eslint": "^8.2.3",
		"babel-loader": "^7.1.4",
		"babel-plugin-transform-class-properties": "^6.24.1",
		"babel-plugin-transform-decorators-legacy": "^1.3.5",
		"babel-plugin-transform-runtime": "^6.23.0",
		"babel-preset-env": "^1.7.0",
		"babel-preset-stage-0": "^6.16.0",
		"babel-preset-stage-1": "^6.24.1",
		"babel-register": "^6.26.0",
		"babel-runtime": "^6.26.0",
		"babelify": "^8.0.0",
		"body-parser": "^1.18.3",
		"bootstrap-sass": "^3.3.7",
		"bourbon": "~5.0.1",
		"bourbon-neat": "^2.0.1",
		"browser-sync": "^2.24.4",
		"case-sensitive-paths-webpack-plugin": "^2.1.2",
		"chalk": "^2.4.1",
		"command-line-args": "^4.0.7",
		"command-line-usage": "^4.0.2",
		"connect-browser-sync": "^2.1.0",
		"copy-webpack-plugin": "^4.5.1",
		"cross-env": "^5.2.0",
		"css-loader": "^0.28.11",
		"deep-extend": "^0.6.0",
		"dr-svg-sprites": "^1.0.0",
		"eslint": "^4.19.1",
		"eslint-config-prettier": "^2.9.0",
		"eslint-plugin-prettier": "^2.6.0",
		"express": "^4.15.3",
		"faker": "^4.1.0",
		"globby": "^8.0.1",
		"husky": "^1.0.0-rc.1",
		"include-media": "^1.4.8",
		"jshint-stylish": "^2.0.0",
		"lodash": "^4.17.15",
		"mangony": "^1.6.1",
		"mangony-hbs-helpers": "^0.6.2",
		"mini-css-extract-plugin": "^0.4.0",
		"mkdirp": "^0.5.1",
		"morgan": "^1.8.2",
		"node-sass": "^4.13.1",
		"node-sass-magic-importer": "^5.1.3",
		"nodemon": "^1.17.5",
		"npm-run-all": "^4.1.3",
		"optimize-css-assets-webpack-plugin": "^4.0.2",
		"postcss-loader": "^2.1.5",
		"prettier": "^1.13.5",
		"request": "^2.87.0",
		"responsive-images-generator": "^0.2.2",
		"rimraf": "^2.6.2",
		"sass-loader": "^7.0.3",
		"style-loader": "^0.21.0",
		"stylelint": "^9.3.0",
		"vue-loader": "^15.6.2",
		"vue-style-loader": "^4.1.2",
		"webpack": "^4.12.0",
		"webpack-cli": "^3.0.8",
		"winston": "^2.3.1"
	},
	"licenses": [
		{
			"type": "MIT"
		}
	],
	"keywords": []
}

>

**Comment by Sebastian-Fitzner** [comment]
Are you using all plugins? If so, you should replace the store. It is deprecated. Besides of the store you can update without any further issues...
